### ISSUE TITLE
wrong value for ALL_EVENT 

### ISSUE THREAD

**Issue by benzinerwin** [sunmingshi/Jinotify#2]
file: Jinotify/src/main/java/com/megacreep/jinotify/Mask.java 
line 16 is:
public static final int ALL_EVENT = 4096;
should be:
public static final int ALL_EVENT = 4095;
---
Thank you for sharing the code!
I did not find a way to contact you, so I hope it's ok to ask you here: am I allowed to use your code in my own projects? If so, what are the terms (license)? Thank you & kind regards!

**Comment by sunmingshi** [comment]
It's Completely free with no terms or license
